name: Update Deposits CSV

on:
  schedule:
    - cron: '0 14 * * *'  
    - cron: '0 20 * * *'  
    - cron: '0 31 * * *'  
  workflow_dispatch:  

jobs:
  update-deposits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas

      - name: Run deposit update script
        run: python update_deposits.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add deposit.csv
          git commit -m "Automated deposit update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
